name = "h2_frame"
version = "0.2.1"

description = "An HTTP/2 frame encoder and decoder for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "Alge", repo = "h2_frame" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
